MovieFinder/Models/Movie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieFinder.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "nvarchar(200)")]
        public string Name { get; set; } = null!;
        public DateTime Premiere { get; set; }
        [Column(TypeName = "nvarchar(200)")]
        public string Country { get; set; } = null!;
        [Column(TypeName = "nvarchar(200)")]
        public string Studio { get; set; } = null!;
        [Column(TypeName = "nvarchar(200)")]
        public string Producer { get; set; } = null!;
        public string FullDescription { get; set; } = null!;
        [Column(TypeName = "nvarchar(1000)")]
        public string ShortDescription { get; set; } = null!;
        public float Money { get; set; }
       

        public virtual List<Actor> Actors { get; set; }
        public virtual List<WorldRating> WorldRatings { get; set; }
        public virtual List<Genre> Genres { get; set; }
        public virtual List<Like> Likes { get; set; }
        public virtual List<Dislike> Dislikes { get; set; }
        public virtual List<Viewing> Viewings { get; set; }
        public virtual List<Image> Images { get; set; }
        public virtual List<MovieFact> MovieFacts { get; set; }
        public virtual List<Comment> Comments { get; set; }


       
        public virtual Image Image { get; set; }

    }
}

MovieFinder/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieFinder.Models;
using MovieFinder.Models.Forms;
using MovieFinder.Services.DataServices;
using MovieFinder.Services.ImageServices;


namespace MovieFinder.Controllers
{
    [Authorize(Roles ="Admin , Manager")]
    public class DashboardController : Controller
    {
        public IMovieDbProvider DBProvider { get; set; }
        public IImageProvider _imageManager { get; set; }
        public DashboardController(IMovieDbProvider provider,IImageProvider imageManager)
        {
            DBProvider = provider;
            _imageManager = imageManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MoviesManager()
        {
           
            List<Movie> movies=DBProvider.GetMovies().ToList();
           

            return View(movies);
        }
        [HttpGet]
        public async Task<IActionResult> CreateMoviesManager()
        {
            ViewData["Actors"] = DBProvider.GetActors().ToList();
            ViewData["WorldRatingNames"] = DBProvider.GetWorldRatingNames().ToList();
            ViewData["GenreNames"] = DBProvider.GetGenreNames().ToList();
            return View(new AddMovieForm());
        }

        [HttpPost]
        public async Task<IActionResult> CreateMoviesManager([FromForm]AddMovieForm addMovieForm)
        {
            var newMovie=new Movie();
            newMovie.Name = addMovieForm.Name;
            newMovie.Premiere = addMovieForm.Premiere;
            newMovie.Country = addMovieForm.Country;
            newMovie.Studio = addMovieForm.Studio;
            newMovie.Producer = addMovieForm.Producer;
            newMovie.FullDescription = addMovieForm.FullDescription;
            newMovie.ShortDescription = addMovieForm.ShortDescription;
            newMovie.Money = addMovieForm.Money;
            if(addMovieForm.Image != null)
            {
                var image=await _imageManager.SaveUploadedFile(addMovieForm.Image);
                DBProvider.CreateImage(image);
                newMovie.Image = image;
            }
            //newMovie.Actors=addMovieForm.Actors;
            if (addMovieForm.Actors != null)
            {
                List<Actor> actors = new List<Actor>();
                foreach (var actor in addMovieForm.Actors)
                {
                    var actorToList = DBProvider.GetActor(actor);
                   
                    actors.Add(actorToList);

                }
                newMovie.Actors = actors;
            }
            if (addMovieForm.WorldRatingNames != null)
            {
                List<WorldRating> ratings = new List<WorldRating>();
                foreach (var rating in addMovieForm.WorldRatingNames)
                {
                    var name=DBProvider.GetWorldRatingName(rating).Name;
                    var newRating = new WorldRating() { Name = name };
                    ratings.Add(newRating);

                }
                newMovie.WorldRatings = ratings;
            }

            if (addMovieForm.GenreNames != null)
            {
                List<Genre> genres = new List<Genre>();
                foreach (var genre in addMovieForm.GenreNames)
                {
                    var name = DBProvider.GetGenreName(genre).Name;
                    var newGenre = new Genre() { Name = name };
                    genres.Add(newGenre);

                }
                newMovie.Genres = genres;
            }

            newMovie.Likes=addMovieForm.Likes;
            newMovie.Dislikes=addMovieForm.Dislikes;
            newMovie.Viewings=addMovieForm.Viewings;
            if(addMovieForm.Images!=null)
            {
                newMovie.Images=new List<Models.Image>();
                foreach(var image in addMovieForm.Images)
                {
                    var newImage = await _imageManager.SaveUploadedFile(image);
                    DBProvider.CreateImage(newImage);
                    newMovie.Images.Add(newImage);
                }
            }
            newMovie.MovieFacts=addMovieForm.MovieFacts;
            newMovie.Comments=addMovieForm.Comments;


            DBProvider.CreateMovie(newMovie);

            return RedirectToAction("MoviesManager"); 
        }
        public IActionResult ActorsManager()
        {
            var actors=DBProvider.GetActors().ToList();
            return View(actors);
        }
        public IActionResult CreateActorManager()
        {
            ViewData["Movies"] = DBProvider.GetMovies().ToList();
            ViewData["ActorFacts"] = DBProvider.GetActorFacts().ToList();
            return View(new AddActorForm());
        }
        [HttpPost]
        public async Task<IActionResult> CreateActorManager([FromForm] AddActorForm form)
        {
            var newActor = new Actor();
            newActor.Name = form.Name;
            newActor.LastName = form.LastName;
            newActor.Birthday = form.Birthday;
            newActor.Country = form.Country;
            newActor.Biography = form.Biography;    
            if(form.Image != null)
            {
                var image =await _imageManager.SaveUploadedFile(form.Image);
                DBProvider.CreateImage(image);
                newActor.Image = image;
            }
            if(form.Movies!=null)
            {
                newActor.Movies = new List<Movie>();
                foreach (var id in form.Movies)
                {
                    var movie=DBProvider.GetMovie(id);
                    
                    newActor.Movies.Add(movie);
                }
            }
            if (form.ActorFacts != null)
            {
                newActor.ActorFacts = new List<ActorFact>();
                foreach (var id in form.ActorFacts)
                {
                    var fact = DBProvider.GetActorFact(id);
                    
                    newActor.ActorFacts.Add(fact);
                }
            }
            DBProvider.CreateActor(newActor);
            return RedirectToAction("ActorsManager");
        }
        public IActionResult GenreNameManager()
        {
            List<GenreName> genres=DBProvider.GetGenreNames().ToList();
            return View(genres);
        }

        public IActionResult CreateGenreNameManager()
        {
            
            return View(new AddGenreNameForm());
        }
        [HttpPost]
        public IActionResult CreateGenreNameManager([FromForm]AddGenreNameForm form)
        {
            GenreName newForm = new GenreName();
            newForm.Name = form.Name;
            DBProvider.CreateGenreName(newForm);
            return RedirectToAction("GenreNameManager");
        }


        public IActionResult WorldRatingNameManager()
        {
            List<WorldRatingName> ratings = DBProvider.GetWorldRatingNames().ToList();
            return View(ratings);
        }

        public IActionResult CreateWorldRatingNameManager()
        {

            return View(new AddWorldRatingNameForm());
        }
        [HttpPost]
        public IActionResult CreateWorldRatingNameManager([FromForm] AddWorldRatingNameForm form)
        {
            WorldRatingName newForm = new WorldRatingName();
            newForm.Name = form.Name;
            DBProvider.CreateWorldRatingName(newForm);
            return RedirectToAction("WorldRatingNameManager");
        }

        public IActionResult DeleteMovie(int id)
        {
            var movie=DBProvider.GetMovie(id);
            var image=movie.Image;
            _imageManager.RemoveFile(image);
            foreach (var item in movie.Likes)
            {
                DBProvider.DeleteLike(item.Id);
            }
            foreach (var item in movie.Dislikes)
            {
                DBProvider.DeleteDislike(item.Id);
            }
            DBProvider.DeleteImage(image.Id);
            DBProvider.DeleteMovie(id);
            return RedirectToAction("MoviesManager");
        }

        public IActionResult DeleteActor(int id)
        {
            var actor = DBProvider.GetActor(id);
            var image = actor.Image;
            _imageManager.RemoveFile(image);
            
            DBProvider.DeleteImage(image.Id);
            DBProvider.DeleteActor(id);
            return RedirectToAction("ActorsManager");
        }

        public IActionResult DeleteGenreName(int id)
        {

            var genreName=DBProvider.GetGenreName(id).Name;
            var genresToDelete=DBProvider.GetGenres().Where(x => x.Name == genreName);
            foreach (var item in genresToDelete)
            {
                DBProvider.DeleteGenre(item.Id);
            }
            DBProvider.DeleteGenreName(id);
            
            return RedirectToAction("GenreNameManager");
        }

        public IActionResult DeleteWorldRatingName(int id)
        {

            var ratingName = DBProvider.GetWorldRatingName(id).Name;
            var ratingToDelete = DBProvider.GetWorldRatings().Where(x => x.Name == ratingName);
            foreach (var item in ratingToDelete)
            {
                DBProvider.DeleteWorldRating(item.Id);
            }
            DBProvider.DeleteWorldRatingName(id);

            return RedirectToAction("WorldRatingNameManager");
        }
        [HttpGet]
        public IActionResult EditActor(int id)
        {
            var actor=DBProvider.GetActor(id);
            ViewData["Movies"] = DBProvider.GetMovies().ToList();
            ViewData["ActorFacts"] = DBProvider.GetActorFacts().ToList();

            return View(new AddActorForm(actor));
        }

        [HttpPost]
        public async  Task<IActionResult> EditActor([FromForm] AddActorForm form)
        {
            var updatedActor=DBProvider.GetActor(form.Id);
            
            //updatedActor.Id = form.Id;
            updatedActor.Name = form.Name;
            updatedActor.LastName = form.LastName;

MovieFinder/Controllers/MovieController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieFinder.Models;
using MovieFinder.Services.DataServices;

using System.Security.Claims;

namespace MovieFinder.Controllers
{
    public class MovieController : Controller
    {
        private IMovieDbProvider _DBProvider;
        private readonly UserManager<User> _userManager;
        public MovieController(IMovieDbProvider DBProvider, UserManager<User> manager)
        {
                _DBProvider = DBProvider;
            _userManager = manager;
        }
        public IActionResult Index()
        {
            var movies=_DBProvider.GetMovies();
            
            return View(movies);
        }

        public IActionResult ShowMovie(int id)
        {
            var movie = _DBProvider.GetMovie(id);
            ViewData["SimilarMovies"] = _DBProvider.GetMovies().ToList();


            return View(movie);
        }
        public async Task<IActionResult> AddLike(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("ShowMovie", new { id });
            }
            var likes=_DBProvider.GetLikes().Where(x=>x.MovieId == id).Where(x=>x.UserId==currentUser.Id).ToList();
            if(likes.Count==0 && currentUser != null)
            {
                var newLike = new Like();
                newLike.ClickDate = DateTime.Now;
                newLike.Movie = _DBProvider.GetMovie(id);

                newLike.User = currentUser;
                _DBProvider.CreateLike(newLike);
            }
            
            return RedirectToAction("ShowMovie",new { id });
        }

        public async Task<IActionResult> AddDislike(int id)
        {


            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("ShowMovie", new { id });
            }
            var Dislikes = _DBProvider.GetDislikes().Where(x => x.MovieId == id).Where(x => x.UserId == currentUser.Id).ToList();
            if (Dislikes.Count == 0&&currentUser!=null)
            {
                var newDislike = new Dislike();
                newDislike.ClickDate = DateTime.Now;
                newDislike.Movie = _DBProvider.GetMovie(id);
                newDislike.User = currentUser;
                _DBProvider.CreateDislike(newDislike);
            }
            return RedirectToAction("ShowMovie", new { id });
        }

        [HttpPost]
        
        public IActionResult SearchMovies()
        {
            string value = Request.Form["Search"];
            var movies = _DBProvider.GetMovies().Where(x => x.Name.ToLower().Contains(value.ToLower()) ||
            x.ShortDescription.ToLower().Contains(value.ToLower()) ||
            x.FullDescription.ToLower().Contains(value.ToLower()) ||
            x.Producer.ToLower().Contains(value.ToLower()) ||
            x.Studio.ToLower().Contains(value.ToLower())).ToList();
            

            
            

            return View(movies);
        }


    }
}

MovieFinder/Views/Movie/Index.cshtml
@model List<Movie>
@{
   
}
<section class="text-gray-100 body-font">
    <div class="container px-5 py-24 mx-auto">

        <div class="container px-5 py-24 mx-auto inline-flex">

            @foreach (var movie in Model)
            {
                <div class="flex w-1/3 ">
                    <div class="p-4 w-full">
                        <div class="h-full border-2 border-gray-800 rounded-lg overflow-hidden">
                            <div class="lg:h-34 md:h-26 w-full p-1">
                                @if (movie.Image != null)
                                {
                                    <img class="m-auto h-64  object-center rounded-lg" src='@movie.Image.Path' alt="poster">
                                }
                                else
                                {
                                    <img class="lg:h-34 md:h-26 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
                                }

                            </div>

                            <div class="p-6">
                                <h1 class="title-font text-lg font-medium text-white mb-3">@movie.Name</h1>
                                <div class="flex">
                                    @if (movie.Genres != null)
                                    {
                                        @foreach (var genre in movie.Genres)
                                        {
                                            var genreName = @genre.Name + "| ";
                                            <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">@genreName </h2>

                                        }
                                    }

                                </div>



                                <p class="leading-relaxed mb-3">@movie.ShortDescription</p>
                                <div class="flex items-center flex-wrap ">
                                    <a asp-controller="Movie" asp-action="ShowMovie" asp-route-id="@movie.Id" class="text-yellow-400 inline-flex items-center md:mb-2 lg:mb-0">
                                        Read More
                                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14"></path>
                                            <path d="M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                    <span class="text-gray-500 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-800">
                                        
                                        <a asp-controller="Dashboard" asp-action="CreateLike">
                                            Likes:
                                        </a>
                                        @if (movie.Likes != null)
                                        {
                                            @movie.Likes.Count
                                        }
                                    </span>
                                    <span class="text-gray-500 inline-flex items-center leading-none text-sm">
                                        <a asp-controller="Dashboard" asp-action="CreateDislike" >
                                            Disikes:
                                        </a>
                                        @if (movie.Dislikes != null)
                                        {
                                            @movie.Dislikes.Count
                                        }
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            }


        </div>



    </div>
</section>

MovieFinder/Views/Movie/SearchMovies.cshtml
@model List<Movie>
@{
   
}
<section class="text-gray-100 body-font">
    <div class="container px-5 py-24 mx-auto">

        <div class="container px-5 py-24 mx-auto inline-flex">

            @foreach (var movie in Model)
            {
                <div class="flex w-1/3 ">
                    <div class="p-4 w-full">
                        <div class="h-full border-2 border-gray-800 rounded-lg overflow-hidden">
                            <div class="lg:h-34 md:h-26 w-full p-1">
                                @if (movie.Image != null)
                                {
                                    <img class="m-auto h-64  object-center rounded-lg" src='@movie.Image.Path' alt="poster">
                                }
                                else
                                {
                                    <img class="lg:h-34 md:h-26 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
                                }

                            </div>

                            <div class="p-6">
                                <h1 class="title-font text-lg font-medium text-white mb-3">@movie.Name</h1>
                                <div class="flex">
                                    @if (movie.Genres != null)
                                    {
                                        @foreach (var genre in movie.Genres)
                                        {
                                            var genreName = @genre.Name + "| ";
                                            <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">@genreName </h2>

                                        }
                                    }

                                </div>



                                <p class="leading-relaxed mb-3">@movie.ShortDescription</p>
                                <div class="flex items-center flex-wrap ">
                                    <a asp-controller="Movie" asp-action="ShowMovie" asp-route-id="@movie.Id" class="text-yellow-400 inline-flex items-center md:mb-2 lg:mb-0">
                                        Read More
                                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14"></path>
                                            <path d="M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                    <span class="text-gray-500 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-800">
                                        
                                        <a asp-controller="Dashboard" asp-action="CreateLike">
                                            Likes:
                                        </a>
                                        @if (movie.Likes != null)
                                        {
                                            @movie.Likes.Count
                                        }
                                    </span>
                                    <span class="text-gray-500 inline-flex items-center leading-none text-sm">
                                        <a asp-controller="Dashboard" asp-action="CreateDislike" >
                                            Disikes:
                                        </a>
                                        @if (movie.Dislikes != null)
                                        {
                                            @movie.Dislikes.Count
                                        }
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            }


        </div>



    </div>
</section>

MovieFinder/Views/Movie/ShowMovie.cshtml
@model Movie
@{
    var m = Model;
    var movies = ViewData["SimilarMovies"] as List<Movie>;
}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src=@m.Image.Path>
        <div class="text-center lg:w-2/3 w-full">
            <div>
                <a asp-controller="Movie" asp-action="AddLike" asp-route-id="@m.Id" class="mr-5 hover:text-amber-400  hover:font-bold">LIKE</a>
                <a asp-controller="Movie" asp-action="AddDislike" asp-route-id="@m.Id" class="mr-5 hover:text-amber-400  hover:font-bold">DISLIKE</a>
            </div>
            <div class="flex justify-center">
                <div class="text-gray-400 bg-gray-900 body-font">
                    <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
                        <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
                            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">@m.Name</h1>
                            <p class="mt-2 text-sm text-gray-500">@m.Country @m.Premiere.Year @m.Studio @m.Producer</p>
                        </div>
                        <div class="flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center">
                            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                                <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">ACTORS</h2>
                                <nav class="list-none mb-10">
                                    @foreach(var actor in m.Actors)
                                    {
                                        <li>
                                            <a class="text-gray-400 hover:text-white">@actor.Name @actor.LastName</a>
                                        </li>
                                    }                                  
                                </nav>
                            </div>
                            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                                <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">GENRES</h2>
                                <nav class="list-none mb-10">
                                    @foreach (var genre in m.Genres)
                                    {
                                        <li>
                                            <a class="text-gray-400 hover:text-white">@genre.Name</a>
                                        </li>
                                    }
                                </nav>
                            </div>
                            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                                <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">RATINGS</h2>
                                <nav class="list-none mb-10">
                                    @foreach (var rating in m.WorldRatings)
                                    {
                                        <li>
                                            <a class="text-gray-400 hover:text-white">@rating.Name </a>
                                        </li>
                                    }
                                </nav>
                            </div>
                            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                                <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">Likes</h2>
                                <nav class="list-none mb-10">
                                    <li>
                                        <p class="text-gray-400 hover:text-white">Likes: @m.Likes.Count </p>
                                    </li>
                                    <li>
                                        <p class="text-gray-400 hover:text-white">Dislikes: @m.Dislikes.Count</p>
                                    </li>

                                </nav>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
            <p class="leading-relaxed mb-8">@m.FullDescription</p>
            
           
        </div>
    </div>
    <div>
        <p class="m-auto">Similar movies</p>
        <div class="grid grid-cols-4 gap-4">

            @foreach (var movie in movies)
            {
                <div class="border-2 border-gray-800 rounded-lg overflow-hidden">
                   
                            <div class="lg:h-34 md:h-26 w-full p-1">
                                @if (movie.Image != null)
                                {
                                    <img class="m-auto h-64  object-center rounded-lg" src='@movie.Image.Path' alt="poster">
                                }
                                else
                                {
                                    <img class="lg:h-34 md:h-26 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
                                }

                            </div>

                            <div class="p-6">
                                <h1 class="title-font text-lg font-medium text-white mb-3">@movie.Name</h1>
                                <div class="flex">
                                    @if (movie.Genres != null)
                                    {
                                        @foreach (var genre in movie.Genres)
                                        {
                                            var genreName = @genre.Name + "| ";
                                            <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">@genreName </h2>

                                        }
                                    }

                                </div>



                                <p class="leading-relaxed mb-3">@movie.ShortDescription</p>
                                <div class="flex items-center flex-wrap ">
                                    <a class="text-yellow-400 inline-flex items-center md:mb-2 lg:mb-0">
                                        Read More
                                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14"></path>
                                            <path d="M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                    <span class="text-gray-500 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-800">
                                        Likes:
                                        @if (movie.Likes != null)
                                        {
                                            @movie.Likes.Count
                                        }
                                    </span>
                                    <span class="text-gray-500 inline-flex items-center leading-none text-sm">
                                        Dislikes:
                                        @if (movie.Dislikes != null)
                                        {
                                            @movie.Dislikes.Count
                                        }
                                    </span>
                                </div>
                            </div>
                        </div>
                    

                
            }


        </div>
    </div>
</section>