MovieFinder/Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;

using MovieFinder.Services.DataServices;

namespace MovieFinder.Controllers
{
    public class ActorController : Controller
    {
        private IMovieDbProvider _DBProvider;
        public ActorController(IMovieDbProvider DBProvider)
        {
                _DBProvider = DBProvider;
        }
        public IActionResult Index()
        {
            var actors=_DBProvider.GetActors();
            
            return View(actors);
        }

        public IActionResult ShowActor(int id)
        {
            var actor = _DBProvider.GetActor(id);
            


            return View(actor);
        }
    }
}

MovieFinder/Controllers/MovieController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieFinder.Models;
using MovieFinder.Services.DataServices;

using System.Security.Claims;

namespace MovieFinder.Controllers
{
    public class MovieController : Controller
    {
        private IMovieDbProvider _DBProvider;
        private readonly UserManager<User> _userManager;
        public MovieController(IMovieDbProvider DBProvider, UserManager<User> manager)
        {
                _DBProvider = DBProvider;
            _userManager = manager;
        }
        public IActionResult Index()
        {
            var movies=_DBProvider.GetMovies();
            
            return View(movies);
        }

        public IActionResult ShowMovie(int id)
        {
            var movie = _DBProvider.GetMovie(id);
            ViewData["SimilarMovies"] = _DBProvider.GetMovies().ToList();


            return View(movie);
        }
        public async Task<IActionResult> AddLike(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("ShowMovie", new { id });
            }
            var likes=_DBProvider.GetLikes().Where(x=>x.MovieId == id).Where(x=>x.UserId==currentUser.Id).ToList();
            if(likes.Count==0 && currentUser != null)
            {
                var newLike = new Like();
                newLike.ClickDate = DateTime.Now;
                newLike.Movie = _DBProvider.GetMovie(id);

                newLike.User = currentUser;
                _DBProvider.CreateLike(newLike);
            }
            
            return RedirectToAction("ShowMovie",new { id });
        }

        public async Task<IActionResult> AddDislike(int id)
        {


            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("ShowMovie", new { id });
            }
            var Dislikes = _DBProvider.GetDislikes().Where(x => x.MovieId == id).Where(x => x.UserId == currentUser.Id).ToList();
            if (Dislikes.Count == 0&&currentUser!=null)
            {
                var newDislike = new Dislike();
                newDislike.ClickDate = DateTime.Now;
                newDislike.Movie = _DBProvider.GetMovie(id);
                newDislike.User = currentUser;
                _DBProvider.CreateDislike(newDislike);
            }
            return RedirectToAction("ShowMovie", new { id });
        }

        [HttpPost]
        
        public IActionResult SearchMovies()
        {
            string value = Request.Form["Search"];
            var movies = _DBProvider.GetMovies().Where(x => x.Name.ToLower().Contains(value.ToLower()) ||
            x.ShortDescription.ToLower().Contains(value.ToLower()) ||
            x.FullDescription.ToLower().Contains(value.ToLower()) ||
            x.Producer.ToLower().Contains(value.ToLower()) ||
            x.Studio.ToLower().Contains(value.ToLower())).ToList();
            

            
            

            return View(movies);
        }


    }
}

MovieFinder/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieFinder.Models;
using MovieFinder.Models.Forms;

namespace MovieFinder.Controllers
{

    
    public class RolesController : Controller
    {

        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole<int>> _roleManager;
        public RolesController(UserManager<User> userManager, RoleManager<IdentityRole<int>> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

        }
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> ShowRoles()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> CreateRole()
        {
            return View(new RoleForm());
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole([FromForm] RoleForm form)
        {

            var newRoleName = form.Name;
            
                var newRole = new IdentityRole<int>();
                newRole.Name = newRoleName;
                await _roleManager.CreateAsync(newRole);
            
            return RedirectToAction("ShowRoles");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var roleToDelete = await _roleManager.FindByIdAsync(id.ToString());
            if (roleToDelete != null)
            {
                await _roleManager.DeleteAsync(roleToDelete);
            }
            return RedirectToAction("ShowRoles");
        }
    }
}

MovieFinder/Views/Shared/_DashboardNavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
            <a asp-controller="Dashboard" asp-action="MoviesManager" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">Movies</a>
            <a asp-controller="Dashboard" asp-action="ActorsManager" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">Actors</a>
            <a asp-controller="Dashboard" asp-action="GenreNameManager" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">Genres</a>
            
            <a asp-controller="User" asp-action="ShowUsers" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">Users</a>
            <a asp-controller="Roles" asp-action="ShowRoles" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">Roles</a>
            <a asp-controller="Dashboard" asp-action="WorldRatingNameManager" class="mr-5 text-lg hover:text-amber-400 hover:text-xl hover:font-bold nav-link">WorldRatings</a>
        </nav>
    </div>
</div>

MovieFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieFinder</title>
    <link rel="stylesheet" href="~/css/tailwind.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieFinder.styles.css" asp-append-version="true" /> *@
    
    

</head>
<body class="bg-neutral-900">
   <header>      
       <partial name="_NavBar"/>
   </header>
       
    @RenderBody()
       
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   @*  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieFinder/Views/Shared/_NavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="bg-neutral-900  text-amber-100 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a class="flex title-font font-medium items-center text-amber-200 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-yellow-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">MovieFinder</span>
        </a>
        <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
            <a asp-controller="Home" asp-action="Index" class="mr-5 hover:text-amber-400 hover:font-bold nav-link">Home</a>
            <a asp-controller="Movie" asp-action="Index" class="mr-5 hover:text-amber-400  hover:font-bold">Movies</a>
            
            <a asp-controller="Actor" asp-action="Index" class="mr-5 hover:text-amber-400  hover:font-bold">Actors</a>
        </nav>
       <div class="text-gray-600 body-font mr-5">
            <form class=" text-center w-full " role="search" asp-controller="Movie" asp-action="SearchMovies">
                <input class="h-5 bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-yellow-500 focus:bg-transparent focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" type="search" placeholder="Search" aria-label="Search" name="Search">
                <button class="text-white pr-2 pl-2 bg-amber-400 border-0 focus:outline-none hover:bg-yellow-600 rounded text-sm" type="submit">Search</button>
            </form>
        </div>
        <div>
            @if(User.Identity.IsAuthenticated)
            {
                <a asp-controller="Dashboard" asp-action="Index" class="mr-5 hover:text-amber-400 nav-link hover:font-bold">Dashboard</a>
            }
            
            @if(User.Identity.IsAuthenticated)
            {
                <a asp-controller="User" asp-action="Logout" class="mr-5 hover:text-amber-400 hover:font-bold">Logout</a>
            }
            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-controller="User" asp-action="Login" class="mr-5 hover:text-amber-400 hover:font-bold">Login</a>
                <a asp-controller="User" asp-action="Register" class="mr-5 hover:text-amber-400 hover:font-bold">Register</a>
            }

            @if(User.Identity.IsAuthenticated)
            {
                <span>User: @User.Identity.Name</span>
            }
           
            
        </div>
       
    </div>
</div>